### PR TITLE
Espresso tests for survey toolbar

### PR DESCRIPTION
**Pull request by Chinex-Boroja**
### Overview
The Survey App toolbar was recently revised and updated, so there are needs to write tests to ensure the App is behaving as expected

### The Survey App's functionality tested

- `testToolbarLogoNavigation()`
- `testSyncMenuItem()`
- `testSettingsMenuItem()`

### Screenshot of passed Tests on Android Studio
IntegrationTests

### CODE REVIEW

**Review by wbrunette — CHANGES_REQUESTED** [review]
The tests do not pass on the build server (CircleCI).

org.opendatakit.survey.logic.TestMainMenuActivity > testSettingsMenuItem[avd(AVD) - 11] FAILED 
        androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: view.getId() is <2131361857/org.opendatakit.survey:id/action_settings>


org.opendatakit.survey.logic.TestMainMenuActivity > testSyncMenuItem[avd(AVD) - 11] FAILED 
        androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: view.getId() is <2131361858/org.opendatakit.survey:id/action_sync>

**Comment by wbrunette** [comment]
Some of these fixes have now been made. Make sure to merge changes back to your update-jdk11 branch. Check out a similar PR that was merged yesterday that had similar issues.

https://github.com/odk-x/survey/pull/178

**Comment by Chinex-Boroja** [comment]
> Some of these fixes have now been made. Make sure to merge changes back to your update-jdk11 branch. Check out a similar PR that was merged yesterday that had similar issues.
> 
> #178

Alright @wbrunette, will do that

**Comment by Chinex-Boroja** [comment]
Hi @wbrunette tho I merged changes back to my upgrade-jdk11 branch, when I tried following a similar approach from @stryker101 on this [178]( https://github.com/odk-x/survey/pull/178) merged PR on my branch, it still keeps failing on CircleCI, I annotated two other tests with @Ignore annotations, but still failing with the error messages: `org.opendatakit.survey.logic.TestMainMenuActivity > testSyncMenuItem[avd(AVD) - 11] FAILED 
        androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: view.getId() is <2131361858/org.opendatakit.survey:id/action_sync>`

**Comment by wbrunette** [comment]
You should remove the @Ignores from the other test and add @Ignore to rg.opendatakit.survey.logic.TestMainMenuActivity > testSyncMenuItem[avd(AVD) as sync requires Services to be installed.

**Comment by Stryker101** [comment]
> You should remove the @Ignores from the other test and add @Ignore to rg.opendatakit.survey.logic.TestMainMenuActivity > testSyncMenuItem[avd(AVD) as sync requires Services to be installed.

I was curious about this as well. In my PR the test for sync passed without Services being installed. I looked at the implementation and saw that the handling of the intents were both in a try catch block, but they errors were handled differently. Could this be why Sync test passed without Services?

**Comment by Chinex-Boroja** [comment]
> You should remove the @ignores from the other test and add @ignore to rg.opendatakit.survey.logic.TestMainMenuActivity > testSyncMenuItem[avd(AVD) as sync requires Services to be installed.

okay, will try that out in a minute

**Comment by Chinex-Boroja** [comment]
@wbrunette I added the @ignore annotation `org.opendatakit.survey.logic.TestMainMenuActivity > testSyncMenuItem` and `org.opendatakit.survey.logic.TestMainMenuActivity > testSettingsMenuItem` to get the test passing. I think sync and settings require Services to be installed. But I am also wondering why sync test passed on @Stryker101 PR, which he already asked why. Does it have something to do with the try and catch blog?

**Comment by Chinex-Boroja** [comment]
> @wbrunette I added the @ignore annotation `org.opendatakit.survey.logic.TestMainMenuActivity > testSyncMenuItem` and `org.opendatakit.survey.logic.TestMainMenuActivity > testSettingsMenuItem` to get the test passing. I think sync and settings require Services to be installed. But I am also wondering why sync test passed on @Stryker101 PR, which he already asked why. Does it have something to do with the try and catch blog?

Hi @wbrunette Still yet to get a response on this question

**Comment by wbrunette** [comment]
I guess I am confused by the question. Looking at @Stryker101 at his test I do not see a sync test.
https://github.com/odk-x/survey/blob/upgrade-jdk11/survey_app/src/androidTest/java/org/opendatakit/survey/activities/MainMenuActivityTest.java

Your statement "I think sync and settings require Services to be installed. " is correct.

**Comment by Chinex-Boroja** [comment]
> I guess I am confused by the question. Looking at @Stryker101 at his test I do not see a sync test. https://github.com/odk-x/survey/blob/upgrade-jdk11/survey_app/src/androidTest/java/org/opendatakit/survey/activities/MainMenuActivityTest.java
> 
> Your statement "I think sync and settings require Services to be installed. " is correct.

This is it https://github.com/odk-x/survey/blob/upgrade-jdk11/survey_app/src/androidTest/java/org/opendatakit/survey/activities/MainMenuActivityTest.java#L92 @wbrunette

**Comment by wbrunette** [comment]
Intending is actually a Mock that checks the intent is formed correctly:
https://developer.android.com/training/testing/espresso/intents#validation

So it does not need Services installed

**Comment by Chinex-Boroja** [comment]
> Intending is actually a Mock that checks the intent is formed correctly: https://developer.android.com/training/testing/espresso/intents#validation
> 
> So it does not need Services installed

Okay, thanks for the clarification. Will check that out

**Pull request merged**
